// Code generated by "esc -private -o=fs.go -modtime=1546544639 -pkg=schema -include=.*\.json$ -ignore=test-fixtures/* ."; DO NOT EDIT.

package schema

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"os"
	"path"
	"sync"
	"time"
)

type _escLocalFS struct{}

var _escLocal _escLocalFS

type _escStaticFS struct{}

var _escStatic _escStaticFS

type _escDirectory struct {
	fs   http.FileSystem
	name string
}

type _escFile struct {
	compressed string
	size       int64
	modtime    int64
	local      string
	isDir      bool

	once sync.Once
	data []byte
	name string
}

func (_escLocalFS) Open(name string) (http.File, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	return os.Open(f.local)
}

func (_escStaticFS) prepare(name string) (*_escFile, error) {
	f, present := _escData[path.Clean(name)]
	if !present {
		return nil, os.ErrNotExist
	}
	var err error
	f.once.Do(func() {
		f.name = path.Base(name)
		if f.size == 0 {
			return
		}
		var gr *gzip.Reader
		b64 := base64.NewDecoder(base64.StdEncoding, bytes.NewBufferString(f.compressed))
		gr, err = gzip.NewReader(b64)
		if err != nil {
			return
		}
		f.data, err = ioutil.ReadAll(gr)
	})
	if err != nil {
		return nil, err
	}
	return f, nil
}

func (fs _escStaticFS) Open(name string) (http.File, error) {
	f, err := fs.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.File()
}

func (dir _escDirectory) Open(name string) (http.File, error) {
	return dir.fs.Open(dir.name + name)
}

func (f *_escFile) File() (http.File, error) {
	type httpFile struct {
		*bytes.Reader
		*_escFile
	}
	return &httpFile{
		Reader:   bytes.NewReader(f.data),
		_escFile: f,
	}, nil
}

func (f *_escFile) Close() error {
	return nil
}

func (f *_escFile) Readdir(count int) ([]os.FileInfo, error) {
	if !f.isDir {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is not directory", f.name)
	}

	fis, ok := _escDirs[f.local]
	if !ok {
		return nil, fmt.Errorf(" escFile.Readdir: '%s' is directory, but we have no info about content of this dir, local=%s", f.name, f.local)
	}
	limit := count
	if count <= 0 || limit > len(fis) {
		limit = len(fis)
	}

	if len(fis) == 0 && count > 0 {
		return nil, io.EOF
	}

	return []os.FileInfo(fis[0:limit]), nil
}

func (f *_escFile) Stat() (os.FileInfo, error) {
	return f, nil
}

func (f *_escFile) Name() string {
	return f.name
}

func (f *_escFile) Size() int64 {
	return f.size
}

func (f *_escFile) Mode() os.FileMode {
	return 0
}

func (f *_escFile) ModTime() time.Time {
	return time.Unix(f.modtime, 0)
}

func (f *_escFile) IsDir() bool {
	return f.isDir
}

func (f *_escFile) Sys() interface{} {
	return f
}

// _escFS returns a http.Filesystem for the embedded assets. If useLocal is true,
// the filesystem's contents are instead used.
func _escFS(useLocal bool) http.FileSystem {
	if useLocal {
		return _escLocal
	}
	return _escStatic
}

// _escDir returns a http.Filesystem for the embedded assets on a given prefix dir.
// If useLocal is true, the filesystem's contents are instead used.
func _escDir(useLocal bool, name string) http.FileSystem {
	if useLocal {
		return _escDirectory{fs: _escLocal, name: name}
	}
	return _escDirectory{fs: _escStatic, name: name}
}

// _escFSByte returns the named file from the embedded assets. If useLocal is
// true, the filesystem's contents are instead used.
func _escFSByte(useLocal bool, name string) ([]byte, error) {
	if useLocal {
		f, err := _escLocal.Open(name)
		if err != nil {
			return nil, err
		}
		b, err := ioutil.ReadAll(f)
		_ = f.Close()
		return b, err
	}
	f, err := _escStatic.prepare(name)
	if err != nil {
		return nil, err
	}
	return f.data, nil
}

// _escFSMustByte is the same as _escFSByte, but panics if name is not present.
func _escFSMustByte(useLocal bool, name string) []byte {
	b, err := _escFSByte(useLocal, name)
	if err != nil {
		panic(err)
	}
	return b
}

// _escFSString is the string version of _escFSByte.
func _escFSString(useLocal bool, name string) (string, error) {
	b, err := _escFSByte(useLocal, name)
	return string(b), err
}

// _escFSMustString is the string version of _escFSMustByte.
func _escFSMustString(useLocal bool, name string) string {
	return string(_escFSMustByte(useLocal, name))
}

var _escData = map[string]*_escFile{

	"/catalog.schema.json": {
		name:    "catalog.schema.json",
		local:   "catalog.schema.json",
		size:    403,
		modtime: 1546544639,
		compressed: `
H4sIAAAAAAAC/2SQQU7EMAxF9z2FFVjOTNkhdcsNEBcIqafxqBNHtjcR6t1R2hQKs33+78fxVwcA7plG
N4CLZnnoe86YAifzlFD0wjL1GiLefR+8+Zknd9qsjR7Mm3I6b3TVRvFXO7+8Nv+piSNqEMpGnKr8EUkh
C2cUK9BeVvAwkxrwFQQzKxkLoUJkNRyBE1hEEJxITcqlVbcaQnUDrJ+r9Fhw4HVEhvd/rGIrGetuakJp
cr/D5dQ9pryIL3to6X5izsjmNfG+b1Dg7c8R9wr+vGEw1y3ddwAAAP//1dv4AJMBAAA=
`,
	},

	"/errors.schema.json": {
		name:    "errors.schema.json",
		local:   "errors.schema.json",
		size:    1342,
		modtime: 1546544639,
		compressed: `
H4sIAAAAAAAC/5yUTW/aQBCG7/yK0bbHJvRWiZtTnHRVskZgp1KqKtraA2yEd92ZIRKq8t8rf5SgBDDt
deZ5n3ctrff3AADUe1eoEaiVSDUaDkOFPg9erPNIfBloOeR8haUdIlEgVh/aUDvcCz5y8BfttEkVZBdy
8fFTF3/XBQvknFwlLvg6nK4cQ0WhQpItdMUMFtaOBcIC2lYokdkukYFQNuSxgAWFEmSFwEhPSFBsECSA
9eD8k127Agh/bZDlsmvuWhyyGkHz6fW0+6qXST10guWr2VHDyzoPBR5aNDV+U6oRfD+wq9dXk+TqITNf
TfLNtMc9Ck0nSTR+0OYumujxWWyfd6xv4nnaq7yNjL6uwbMOu6PP1p5tzMxdPNPX8XGniW7j3uIG6iud
6/t+Uxrd9DKZibL0SzLT9yfOPY6Njk855tl0mszSeKwOID8O5ZRsq/pWKhZyfvkm9/wmpAoU69bHbvK/
+7p/93+FgxP6XTj8fMRc9sL74I6yRHb7F2rELabEybohks8a4vpJgBlyFTxj93q8Lnoe/AkAAP//7V0L
mj4FAAA=
`,
	},

	"/tags-list.schema.json": {
		name:    "tags-list.schema.json",
		local:   "tags-list.schema.json",
		size:    432,
		modtime: 1546544639,
		compressed: `
H4sIAAAAAAAC/3SQwWrrQAxF9/4KMe8tk0x3BW+7KhS6yQ+otmIr2KNB0saU/HsZe5KaQJc+vudeNN8N
AIT/3IcWwuie2xglU+okOXIitZPoEK0bacboOFic2DwcNm/jO/dqko4bXcVe8eLHl9fa8K+KPVmnnJ0l
Ffk8skFWyaS+QN02QChbIBfAaYIyDpwAQSmLsYsup9pXXSYLLaw3FZpwpt13Qb7kgoK5chpC/XM73JUy
8qSw0/zE/m7al+1TqIrLY655xIKzT2vi8+0dzuXEj9/3vdvydaXOQ3NrfgIAAP//IdRifbABAAA=
`,
	},

	"/": {
		name:  "/",
		local: `.`,
		isDir: true,
	},
}

var _escDirs = map[string][]os.FileInfo{

	".": {
		_escData["/catalog.schema.json"],
		_escData["/errors.schema.json"],
		_escData["/tags-list.schema.json"],
	},
}
