name: conformance-action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v4
      - name: Start a test registry
        run: |
          set -x
          make registry-ci
      - name: Run OCI distribution-spec conformance
        env:
          OCI_REGISTRY: "localhost:5000"
          OCI_TLS: "disable"
          OCI_REPO1: "myorg/myrepo"
          OCI_REPO2: "myorg/myrepo2"
          OCI_RESULTS_DIR: "."
        uses: ./
